### ISSUE TITLE
Not compatible with server information panel

### ISSUE THREAD

**Issue by Wulf-gaming** [DayZ-n-Chill/DayZ-Colorful-UI#7]
As discussed on the discord I think the ifdef needs adding.

**Comment by Wulf-gaming** [comment]
#ifdef ServerPanel <---- where should this string come from i just made a wild guess

**Comment by DrkDevil** [comment]
```
		#ifdef SERVERPANEL
			switch (id)	{
				case SERVER_PANEL:
				menu = GetServerPanelMenu();
				break;
			}
		#endif
```

This is the solution. I am adding in the next patch.

**Comment by DrkDevil** [comment]
Next thing I have noticed is that the menu will now not show up even when this fixe is used.  So I will be adding my own version here shortly.

**Comment by Wulf-gaming** [comment]
#ifdef DayZInformationPanel
			case DIP_PANEL:
				menu = new DayZInformationPanelUI;
				break;
		#endif
		
		#ifdef VanillaPPMap
			case VPP_MENU_MAP:
				menu = new VPPMapMenu;
				break;
		#endif


FIXED i am also using a different information panel which is why i was struggling

**Comment by Wulf-gaming** [comment]
also thought id throw this in here as alot of users still use it 

#ifdef SchanaModParty
		case SCHANA_PARTY_MENU:
				menu = new SchanaPartyMenu;
				break;
		#endif

**Comment by DrkDevil** [comment]
Great I will add these to the compatibility update.

**Comment by Wulf-gaming** [comment]
#ifdef Trader
		case TRADERMENU_UI:
				menu = new TraderMenu;
				break;
		#endif


DR JONES TRADER

**Comment by DrkDevil** [comment]
nice.  any you find that you get working before I can get to them feel free to send a pull request to development.  I will add these as soon as I am feeling better.

**Comment by deannreid** [comment]
Might want to include Lankycraig's Killfeed \ Mod Options in this as this overrides the UI with its modded Esc menu https://steamcommunity.com/sharedfiles/filedetails/?id=2946584843

**Comment by DrkDevil** [comment]
This is closed as a the have all been added.
